language: java
jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "openlenalab"

#### Sonarcloud - openlenalab : jadeu3 needs 
#script:
#  - mvn -B sonar:sonar -DskipTests -Dsonar.projectKey=openlenalab_egovframe-simple-homepage-template
